
```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

# Python

## Environment setup on Unix

Derived from https://ben11kehoe.medium.com/my-python-setup-77c57a2fc4b6 which
is itself derived from https://jacobian.org/2019/nov/11/python-environment-2020/

Also useful: https://lucasrla.github.io/python-on-macos/

1. See system python version: `python3 --version`
1. Install [Homebrew](https://brew.sh)
1. Install pyenv via Homebrew: `brew install pyenv`
1. Follow the [Set up your shell environment for Pyenv](https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv) instructions.
1. Follow the [Suggested build environment](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) instructions.
1. See current python installations (should just be system): `pyenv versions`
1. See list of available python versions in pyenv: `pyenv install --list`
1. Check the latest python version [here](https://www.python.org/downloads/)
1. Install at least the latest version using pyenv: `pyenv install 3.10.6`
1. Check current python installations again: `pyenv versions`
1. Switch to the version you just installed: `pyenv global 3.10.6`
1. List installed packages (should just be pip and setuptools): `pip list`
1. You may be prompted to update pip: `pip install --upgrade pip`
1. Install wheel: `pip install wheel`
1. Install [pipx](https://github.com/pypa/pipx) for installing Python-based CLI programs 
    e.g. youtube-dl: `pip install pipx`
1. Run `pipx ensurepath` and restart shell.
1. Install poetry using pipx: `pipx install poetry`
1. Run the following:

    ```
    poetry config --list
    poetry config virtualenvs.create false
    poetry config --list
    ls ~/Library/Application\ Support/pypoetry
    cat ~/Library/Application\ Support/pypoetry/config.toml
    echo "export POETRY_VIRTUALENVS_IN_PROJECT=1" >> ~/.zshrc
    ```
1. Install JupyterLab using pipx: `pipx install jupyterlab --include-deps`
1. Create a conda config file: `echo "auto_update_conda: False" >> ~/.condarc` 
1. Install latest miniconda using pyenv: `pyenv install miniconda3-latest`
1. Set enable python and miniconda at the same time (order is important!): `pyenv global 3.10.6 miniconda3-latest`
1. Test that miniconda is working: `conda --version`
1. Add some conda channels (in this order!):

    ```
    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
    conda config --show-sources
    ```
1. List conda envs (should be base only at this point): `conda env list`
1. Set conda autoactivate base to false: `conda config --set auto_activate_base false`
1. Initialise conda for using in shell: `conda init zsh`


### Side-notes

#### pip

- Find outdated packages: `pip list --outdated`
- Update an outdated package: `pip install name_of_pkg --upgrade`

#### pipx

pipx is installed in a specific version of Python which is provided by pyenv. 
Then tools installed via pipx are tied to that version. If you get rid of that
python version you may have issues and need to reinstall the tools using 
`pipx reinstall-all`, possibly with the flag `--python xxx`. See
https://lucasrla.github.io/python-on-macos/pipx.html for more info.

- No obvious way to list outdated packages
- Update a package: `pipx upgrade name_of_pkg`
- Update all packages: `pipx upgrade-all`

#### poetry

We have configured poetry to not create virtualenvs for you. I think I'll just
use basic venv for now...

Update poetry: `pipx upgrade poetry`.

Uninstall poetry: `pipx uninstall poetry`.

#### jupyterlab

Run jupyterlab: `jupyter lab`

Check which python version is running:

```
from platform import python_version

print(python_version())
```

List installed packages (without a venv available, Jupyter will use the 
'global' python version which in this case is the version we specified with `pyenv global`):
`!pip list`

Update jupyterlab: `pipx upgrade jupyterlab --include-injected`

Where do jupyter files live?: `jupyter --paths`

## Project setup

...

https://github.com/drivendata/cookiecutter-data-science

https://ealizadeh.com/blog/guide-to-python-env-pkg-dependency-using-conda-poetry

`conda create -n env_name python=3.10`
`conda activate env_name`

Now juypter is installed in its own little environment using pipx. But if we
run jupyter notebooks - `jupyter notebook` - from within our active conda environment,
then we have access to any python package pip installed into the conda env and
any conda package installed into the conda env.

